badgeTemplate = Handlebars.compile([
  "<div class='previewBadge sc-border-dark sc-clearfix' style='display:block; background-color:white; width:auto overflow:hidden;'>",
    "<div class='sc-border-light-bottom sc-clearfix'>",
      "<div class='userImageBadge userBadge__avatar sc-media-image medium' style='float:left;'>",
        "<a href='{{permalink}}'>",
          "<div class='image image__hasPlaceholder image__hasPlaceholder-50 image__hasPlaceholder-user' style='height:50px; width:50px'>",
            "<img src='{{avatar_url}}' class='image__full g-opacity-transition' width='50' height='50'>",
          "</div>",
        "</a>",
      "</div>",
      "<div style='float:right; display:block;'>",
        "<h3 class='userBadge__Title sc-font'>",
          "<a href='{{permalink}}' class='sc-link-dark'>{{username}}</a>",
        "</h3>",
        "<br>",
        "<ul class='stats sc-list-nostyle sc-clearfix userStats stats__large'>",
          "<li class=stats__item>",
            "<span class='sc-ministats-icon-sounds sc-ministats-icon-large sc-border-right-dark sc-ir'>Sounds:</span>",
            "{{track_count}}",
          "</li>",
          "<li class=stats__item>",
            "<span class='sc-ministats-icon-followers sc-ministats-icon-large sc-border-right-dark sc-ir'>Followers:</span>",
            "{{followers_count}}",
          "</li>",
          "<li class=stats__item>",
            "<span class='sc-icon-following sc-icon-large sc-border-right-dark sc-ir'>Followings:</span>",
            "{{followings_count}}",
          "</li>",
        "</ul>",
      "</div>",
    "</div>",
    "<div class='sc-clearfix'>",
      "<span class='userInfo__details sc-text-light sc-border-light-bottom'>",
        "{{full_name}} - {{city}}, {{country}}",
      "</span>",
        "<br>",
      "<span class='userInfo__details sc-text-light sc-truncate'>",
        "{{description}}",
      "</span>",
    "</div>",
  "</div>"].join('\n'));

//todo: add links to the stats: tracks, followers, following, & faves
/////// more info: description, location, ???
/////// fix dimensions - this is probably a late-stage polish once contents are set.
/////// background is wonky
/////// full_name & loc span needs logic/helpers to deal with missing vals.
