badgeTemplate = Handlebars.compile([
    "<div class='previewBadge' style='border:2px; border-color:#ddd'>",
        "<h3 class='userBadge__Title sc-font'>",
            "<a href='{{permalink}}' class='sc-link-dark'",
        "</h3>",
        "<ul class='stats sc-list-nostyle sc-clearfix userStats stats__medium'>",
            "<li class=stats__item>",
                "<span class='sc-ministats-icon-sounds sc-ministats-icon-small sc-ir'>Sounds:</span>",
                "{{track_count}}",
            "</li>",
            "<li class=stats__item>",
                "<span class='sc-ministats-icon-followers sc-ministats-icon-small sc-ir'>Followers:</span>",
                "{{followers_count}}",
            "</li>",
            "<li class=stats__item>",
                "<span class='sc-ministats-icon-followings sc-ministats-icon-small sc-ir'>Followings:</span>",
                "{{followings_count}}",
            "</li>",
        "</ul>",
    "</div>"].join('\n'));
